- hosts: localhost
  become: false
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      become: true
  tasks:
    - include_tasks: tasks/deps.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/node.yml
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/heroku.yml
    - include_tasks: tasks/aws.yml

