- name: Install system packages
  apt:
    name:
      - unzip
      - make
      - cmake
      - gettext
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - g++
      - pkg-config
      - build-essential
      - libssl-dev
      - libbz2-dev
      - zlib1g-dev
      - libreadline-dev
      - libsqlite3-dev
      - llvm
      - curl
      - wget
      - git
      - tmux
      - vim
      - python3-pip
      - stow
      - ripgrep
      - gcc
      - xclip
    state: present
  become: true
  tags:
    - install
    - deps

- name: Clean apt cache
  apt:
    autoclean: yes
  become: true
  tags:
    - install
    - deps

- name: Remove unnecessary packages
  apt:
    autoremove: yes
  become: true
  tags:
    - install
    - deps
