---
- name: Check if fnm is installed
  shell: command -v fnm
  register: fnm_exists
  ignore_errors: yes
  changed_when: false

- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash -s -- --skip-shell
  args:
    creates: "{{ ansible_env.HOME }}/.fnm"
  when: fnm_exists.rc != 0

- name: Add fnm initialization to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # fnm
      FNM_PATH="/home/dantldev/.local/share/fnm"
      if [ -d "$FNM_PATH" ]; then
        export PATH="$FNM_PATH:$PATH"
        eval "`fnm env`"
      fi
    state: present

- name: Install Node.js
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    fnm use --install-if-missing 20
  args:
    executable: /bin/zsh
  register: node_install
  changed_when: "'installed' in node_install.stdout"

- name: Verify Node.js installation
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    node -v
  args:
    executable: /bin/zsh
  register: node_version_check
  changed_when: false

- name: Display Node.js version
  debug:
    var: node_version_check.stdout

- name: Verify npm installation
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    npm -v
  args:
    executable: /bin/zsh
  register: npm_version_check
  changed_when: false

- name: Display npm version
  debug:
    var: npm_version_check.stdout

- name: Install global npm packages
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    npm install -g {{ item }}
  args:
    executable: /bin/zsh
  loop:
    - yarn
    - serve
  register: npm_global_install
  changed_when: "'added' in npm_global_install.stdout"

- name: Verify global npm package installations
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    {{ item }} --version
  args:
    executable: /bin/zsh
  loop:
    - yarn
    - serve
  register: npm_global_versions
  changed_when: false

- name: Display global npm package versions
  debug:
    var: npm_global_versions
