- name: Check if pnpm is installed
  shell: command -v pnpm
  register: pnpm_exists
  ignore_errors: yes
  changed_when: false
  tags:
    - pnpm
    - install

- name: Install pnpm
  shell: curl -fsSL https://get.pnpm.io/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.pnpm-store"
  when: pnpm_exists.rc != 0
  tags:
    - pnpm
    - install

- name: Add pnpm initialization to .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      # pnpm
      export PNPM_HOME="{{ ansible_env.HOME }}/.pnpm-store"
      export PATH="$PNPM_HOME/bin:$PATH"
    state: present
  tags:
    - pnpm
    - install

- name: Verify pnpm installation
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    pnpm --version
  args:
    executable: /bin/zsh
  register: pnpm_version_check
  changed_when: false
  tags:
    - pnpm
    - install